name: qarz_daftari
description: "Qarz va qarzdorlarni boshqarish ilovasi"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.4.7

  sqflite: ^2.3.0
  path: ^1.8.3

  dartz: ^0.10.1

  equatable: ^2.0.5
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#2196F3"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false

  android_12:
    color: "#2196F3"
    image: assets/images/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
